### ISSUE TITLE
How can i chat private like one to one?

### ISSUE THREAD

**Issue by surendrakumarkhatik** [melvin0008/ionic-socketio-chat-client#3]
Hello..
I am new with socket io and io. I want to use this app to one to one chat. How can i do this? Please help
Thanks in advance..

**Comment by melvin0008** [comment]
There are two ways. 
1. Create a unique identifier through which you identify which socket you want to send your message.
   Try [http://stackoverflow.com/questions/7954510/sending-message-to-a-unique-socket](http://stackoverflow.com/questions/7954510/sending-message-to-a-unique-socket)
2. Use [rooms](http://socket.io/docs/rooms-and-namespaces/).
   Create unique rooms each time you need a private chat.
   If you want sample code on this please feel free to browse [Pictionary](https://github.com/melvin0008/Pictionary)

**Comment by surendrakumarkhatik** [comment]
@melvin0008 Thanks for response.
I want to chat app like a client can chat with agent but client must have agent_id, device_id and message.
When agent receive message he reply base on unique device id. How i can do this.

**Comment by surendrakumarkhatik** [comment]
Hey @melvin0008 
I want to like this in nodejs and socket io
https://github.com/fabioberger/Mobile-Live-Chat-Support-Server
Thanks in advance.

**Comment by melvin0008** [comment]
@surendrakumar1992  Just like I mentioned you can add unique identifiers. 

For eg.

On the Client end

``` javascript
var agent_id="xyz",
 devide_id="abc",
 message="pqr";
socket.emit('new_message',sessionId, {message:message,agent_id:agent_id,device_id:device_id});
```

On the server end

``` javascript
socket.on( 'new_message', function(session,data) 
      {
          socket.device_id=data.device_id;
          socket.agent_id=data.agent_id;
          socket.broadcast.to(socket.devide_id).emit('my message', msg);
      });
```

[Reference](http://socket.io/docs/rooms-and-namespaces/#default-room)
