### ISSUE TITLE
Issue regarding socketio

### ISSUE THREAD

**Issue by melvin0008** [melvin0008/ionic-socketio-chat-client#4]
Ref : https://www.airpair.com/ionic-framework/posts/ionic-socketio-chat-application-tutorial
I have a bug when i wrote client socket call used ip , like //172.16.100.174:10010/socket.io/socket.io.js, but seems socket not work when i run ionic for android, any idea?

**Comment by melvin0008** [comment]
Does it work on the browser?

**Comment by mohajer** [comment]
Hello .I have the same problem it works pretty well on browser inside PC and mobile but when i build it and run it in android or emulator it not work.

**Comment by melvin0008** [comment]
The socketio in the code is linked to [http://chat.socket.io/socket.io/socket.io.js](http://chat.socket.io/socket.io/socket.io.js) which works fine. Unfortunately, I cannot recreate your problem.

**Comment by dimiandre** [comment]
Same problem here (i'm using ionic starter from market), 

works only in web and ionic view. 

Android emulator/device isn't working

any ideas ? 

first error 
I/chromium(16642): [INFO:CONSOLE(9)] "Uncaught TypeError: Cannot read property '
Keyboard' of undefined", source: file:///android_asset/www/js/app.js (9)

after commenting keyboard part in app.js 
i get thi sother error
I/chromium(19302): [INFO:CONSOLE(19526)] "ReferenceError: io is not defined
I/chromium(19302):     at Object.<anonymous> (file:///android_asset/www/js/servi
ces/socket.js:3:20)

**Comment by melvin0008** [comment]
Add the ionic keyboard plugin 

``` sh
cordova plugin add com.ionic.keyboard
```

**Comment by melvin0008** [comment]
Sorry to leave this so late.
Cordova updated and external resources needed to be whitelisted inorder for external libraries to work.

So whenever we were connection to chat.socket.io it failed.

So install the cordova plugin

``` sh
cordova plugin add cordova-plugin-whitelist
```

Open config.xml and add two lines in the configuration

```
<allow-navigation href="*" />
<allow-intent href="http://*/*" />
```

This is not advised for production. For production use the links you want to open instead of a wildcard.
