### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by sckoh** [melvin0008/ionic-socketio-chat-client#5]
did you try to run the app on Android?
it is working on browser and iOS
however, when i run it on nexus 5 5.1.1, when I click the Join button, nothing happen, no error

**Comment by melvin0008** [comment]
Yup I tried it on android nexus 5 . 5.1. Why did you close the issue? Did it work?

**Comment by sckoh** [comment]
yes, it works, I'm stupid to point it to the wrong socket server url and it does not throw any error.
thanks.
